// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3i-hhjrTBVBHGCo0dGwzlOeIfJCn7s0k',
    appId: '1:971688621231:web:caa1a84b9d5fad3095905a',
    messagingSenderId: '971688621231',
    projectId: 'sac-app-2cc1d',
    authDomain: 'sac-app-2cc1d.firebaseapp.com',
    storageBucket: 'sac-app-2cc1d.firebasestorage.app',
    measurementId: 'G-MKPL5BBQM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4D3IuVJ1LgIG1BsaEYMeUOtSLWZj24IY',
    appId: '1:971688621231:android:8b186c4e9f6ca05695905a',
    messagingSenderId: '971688621231',
    projectId: 'sac-app-2cc1d',
    storageBucket: 'sac-app-2cc1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAylomI5VfH8RWYssCWeUUJ_dJHG3ZD5fo',
    appId: '1:971688621231:ios:d4868b819e624bd895905a',
    messagingSenderId: '971688621231',
    projectId: 'sac-app-2cc1d',
    storageBucket: 'sac-app-2cc1d.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAylomI5VfH8RWYssCWeUUJ_dJHG3ZD5fo',
    appId: '1:971688621231:ios:d4868b819e624bd895905a',
    messagingSenderId: '971688621231',
    projectId: 'sac-app-2cc1d',
    storageBucket: 'sac-app-2cc1d.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3i-hhjrTBVBHGCo0dGwzlOeIfJCn7s0k',
    appId: '1:971688621231:web:0e7d1ce54575499495905a',
    messagingSenderId: '971688621231',
    projectId: 'sac-app-2cc1d',
    authDomain: 'sac-app-2cc1d.firebaseapp.com',
    storageBucket: 'sac-app-2cc1d.firebasestorage.app',
    measurementId: 'G-NY4Z14B57T',
  );
}
